[phases.setup]
nixPkgs = ['nodejs_20', 'python311', 'python311Packages.pip']

[phases.install]
cmds = [
    'cd nelson-gpt-frontend && npm install -g pnpm && pnpm install',
    'cd nelson-gpt-backend && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd nelson-gpt-frontend && pnpm run build',
    'cp -r nelson-gpt-frontend/dist/* nelson-gpt-backend/src/static/'
]

[start]
cmd = 'cd nelson-gpt-backend && source venv/bin/activate && python src/main.py'

