[phases.setup]
nixPkgs = ['nodejs_20', 'python311', 'python311Packages.pip', 'pnpm']

[phases.install]
cmds = [
    'pnpm install --prefix nelson-gpt-frontend',
    'python -m venv nelson-gpt-backend/venv && nelson-gpt-backend/venv/bin/pip install -r nelson-gpt-backend/requirements-cpu.txt'
]

[phases.build]
cmds = [
    'pnpm run build --prefix nelson-gpt-frontend',
    'mkdir -p nelson-gpt-backend/src/static && cp -r nelson-gpt-frontend/dist/* nelson-gpt-backend/src/static/'
]

[start]
cmd = 'PYTHONPATH=/app/nelson-gpt-backend /app/nelson-gpt-backend/venv/bin/python /app/nelson-gpt-backend/src/main.py'
